=== Shuo-Qi/Shuo-Qi.github.io/Schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.w3school.com.cn" xmlns="http://www.w3school.com.cn" elementFormDefault="qualified">
	<!--定义元素“像素”,类型字符串-->
	<xs:element name="Resolution" type="xs:string"/>
	<!--定义元素“格式”，类型为字符串，默认“jpg”格式-->
	<xs:element name="Format" type="xs:string" default="jpg"/>
	<!--定义元素“大小”，类型为字符串-->
	<xs:element name="Size" type="xs:string"/>
	<!--定义复杂元素“基本信息”,其中属性“时间”可选-->
	<xs:element name="BasicInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Resolution"/>
				<xs:element ref="Format"/>
				<xs:element ref="Size"/>
			</xs:sequence>
			<xs:attribute name="Author" type="xs:string" use="required"/>
			<xs:attribute name="Time" type="xs:date"/>
			<xs:attribute name="Source" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<!--定义元素“介绍”，类型为字符串-->
	<xs:element name="Introduction" type="xs:string"/>
	<!--定义类型“风格名”-->
	<xs:simpleType name="StyleName">
		<xs:restriction base="xs:string">
			<xs:enumeration value="地中海建筑风格"/>
			<xs:enumeration value="意大利建筑风格"/>
			<xs:enumeration value="法式建筑风格"/>
			<xs:enumeration value="英式建筑风格"/>
			<xs:enumeration value="德国建筑风格"/>
			<xs:enumeration value="北美建筑风格"/>
			<xs:enumeration value="新中式建筑风格"/>
			<xs:enumeration value="古典主义建筑风格"/>
			<xs:enumeration value="新古典主义建筑风格"/>
			<xs:enumeration value="现代主义建筑"/>
			<xs:enumeration value="后现代主义风格"/>
			<xs:enumeration value="哥特式建筑风格"/>
			<xs:enumeration value="巴洛克建筑风格"/>
			<xs:enumeration value="洛可可建筑风格"/>
			<xs:enumeration value="园林风格"/>
			<xs:enumeration value="概念式风格"/>
			<xs:enumeration value="综合类建筑风格"/>
		</xs:restriction>
	</xs:simpleType>
	<!--定义类型“类别名”-->
	<xs:simpleType name="ClassificationName">
		<xs:restriction base="xs:string">
			<xs:enumeration value="民族地域"/>
			<xs:enumeration value="历史发展潮流"/>
			<xs:enumeration value="建筑方式"/>
		</xs:restriction>
	</xs:simpleType>
	<!--定义复杂元素“风格”-->
	<xs:element name="Style">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:string">
					<xs:attribute name="name" type="StyleName" use="required"/>
					<xs:attribute name="Classification" type="ClassificationName"/>
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>
	<!--定义复杂元素“详细介绍”-->
	<xs:element name="DetailedInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Introduction"/>
				<xs:element ref="Style"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required"/>
		</xs:complexType>
	</xs:element>
	<!--定义复杂元素“图片”-->
	<xs:element name="Image">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="BasicInfo"/>
				<xs:element ref="DetailedInfo"/>
			</xs:sequence>
			<xs:attribute name="ID" type="xs:integer" use="required"/>
			<xs:attribute name="Downloadable" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Image" minOccurs="1" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Shuo-Qi/Shuo-Qi.github.io/experience_1.0.2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="https://Shuo-Qi.github.io/Data.xsl"?>
<!--DOCTYPE Image SYSTEM "Image.dtd"-->
<!--xml-stylesheet type="text/css" href="https://Shuo-Qi.github.io/css/Data.css"-->
<?xml-stylesheet type="text/xsl" href="https://Shuo-Qi.github.io/Data.xsl"?>
<!--root xmlns="http://www.w3school.com.cn"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://www.w3school.com.cn Schema.xsd"-->

<root>
<!--71116211齐硕部分-->
	<Image ID = "1" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/1.jpg" Time = "2018-08-21">
			<Resolution>425*310</Resolution>
			<Format>jpg</Format>
			<Size>33.9KB</Size>
		</BasicInfo>
		<DetailedInfo name = "普罗旺斯建筑">
			<Introduction>地中海建筑风格闲适、浪漫却不乏宁静是地中海风格建筑所蕴含生活方式的精髓所在。</Introduction>
			<Style name = "地中海建筑风格" Classification = "民族地域">地中海风格建筑，原来是特指沿欧洲地中海北岸沿线的建筑，和当地乡村风格的建筑相结合，产生了诸如法国普罗旺斯、意大利托斯卡纳等地区的经典建筑风格。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "2" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/2.jpg" Time = "2018-08-21">
			<Resolution>318*478</Resolution>
			<Format>jpg</Format>
			<Size>26.0KB</Size>
		</BasicInfo>
		<DetailedInfo name = "托斯卡纳建筑">
			<Introduction>半圆形高大的拱门，或数个连接或垂直交接。</Introduction>
			<Style name = "地中海建筑风格" Classification = "民族地域">地中海风格建筑，原来是特指沿欧洲地中海北岸沿线的建筑，和当地乡村风格的建筑相结合，产生了诸如法国普罗旺斯、意大利托斯卡纳等地区的经典建筑风格。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "3" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/3.jpg" Time = "2018-08-21">
			<Resolution>425*430</Resolution>
			<Format>jpg</Format>
			<Size>27.2KB</Size>
		</BasicInfo>
		<DetailedInfo name = "地中海建筑长廊">
			<Introduction>长长的廊道，延伸至尽头然后垂直拐弯，墙面通过穿凿或半穿凿形成镂空的景致。</Introduction>
			<Style name = "地中海建筑风格" Classification = "民族地域">地中海风格建筑，原来是特指沿欧洲地中海北岸沿线的建筑，和当地乡村风格的建筑相结合，产生了诸如法国普罗旺斯、意大利托斯卡纳等地区的经典建筑风格。
			</Style>
		</DetailedInfo>
	</Image>

	<Image ID = "4" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/4.jpg" Time = "2018-08-21">
			<Resolution>392*479</Resolution>
			<Format>jpg</Format>
			<Size>38.9KB</Size>
		</BasicInfo>
		<DetailedInfo name = "钟塔">
			<Introduction>无论在建筑空间、建筑构件还是建筑外形装饰上，都体现一种次序、一种规律、一种统一的空间概念。</Introduction>
			<Style name = "意大利建筑风格" Classification = "民族地域">意大利建筑风格14世纪意大利出现“文艺复兴”运动，随之资产阶级的象征——市政厅、行会大厦、广场与钟塔等建筑兴起，这就是文艺复兴的意大利建筑风格。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "5" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/5.jpg" Time = "2018-08-21">
			<Resolution>479*313</Resolution>
			<Format>jpg</Format>
			<Size>28.3KB</Size>
		</BasicInfo>
		<DetailedInfo name = "别墅">
			<Introduction>细节的处理上特别细腻精巧，又贴近自然的脉动，使其拥有永恒的生命力。</Introduction>
			<Style name = "意大利建筑风格" Classification = "民族地域">意大利建筑风格14世纪意大利出现“文艺复兴”运动，随之资产阶级的象征——市政厅、行会大厦、广场与钟塔等建筑兴起，这就是文艺复兴的意大利建筑风格。
			</Style>
		</DetailedInfo>
	</Image>

	<Image ID = "6" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/6.jpg" Time = "2018-08-21">
			<Resolution>380*479</Resolution>
			<Format>jpg</Format>
			<Size>38.6KB</Size>
		</BasicInfo>
		<DetailedInfo name = "别墅">
			<Introduction>
阳台、窗间都有铸铁花饰，既保持了罗马建筑特色，又升华了建筑作为住宅的韵味感。尖顶、石柱、浮雕……..彰显着意大利建筑风格古老、雄伟的历史感。
			</Introduction>
			<Style name = "意大利建筑风格" Classification = "民族地域">意大利建筑风格14世纪意大利出现“文艺复兴”运动，随之资产阶级的象征——市政厅、行会大厦、广场与钟塔等建筑兴起，这就是文艺复兴的意大利建筑风格。
			</Style>
		</DetailedInfo>
	</Image>

	<Image ID = "7" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/7.jpg" Time = "2018-08-21">
			<Resolution>462*311</Resolution>
			<Format>jpg</Format>
			<Size>28.9KB</Size>
		</BasicInfo>
		<DetailedInfo name = "屋顶">
			<Introduction>
法式建筑讲究点缀在自然中，并不在乎占地面积的大小，追求色彩和内在的联系，让人感到有很大的活动空间。
			</Introduction>
			<Style name = "法式建筑风格" Classification = "民族地域">法式建筑风格法式建筑往往不求简单的协调，而是崇尚冲突之美，呈现出浪漫典雅风格。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "8" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/8.jpg" Time = "2018-08-21">
			<Resolution>430*479</Resolution>
			<Format>jpg</Format>
			<Size>37.9KB</Size>
		</BasicInfo>
		<DetailedInfo name = "烟囱">
			<Introduction>
对建筑的整体方面有着严格的把握，善于在细节雕琢上下工夫。
			</Introduction>
			<Style name = "法式建筑风格" Classification = "民族地域">法式建筑风格法式建筑往往不求简单的协调，而是崇尚冲突之美，呈现出浪漫典雅风格。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "9" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/9.jpg" Time = "2018-08-21">
			<Resolution>425*335</Resolution>
			<Format>jpg</Format>
			<Size>25.3KB</Size>
		</BasicInfo>
		<DetailedInfo name = "英式别墅">
			<Introduction>
淡绿的草场、深绿的树林、金黄的麦地，点缀着尖顶的教堂和红顶的小楼，构成了英国乡村最基本的图案。
			</Introduction>
			<Style name = "英式建筑风格" Classification = "民族地域">英式建筑风格英式建筑空间灵活适用、流动自然，蓝、灰、绿富有艺术的配色处理赋予建筑动态的韵律与美感。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "10" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/10.jpg" Time = "2018-08-21">
			<Resolution>479*392</Resolution>
			<Format>jpg</Format>
			<Size>33.6KB</Size>
		</BasicInfo>
		<DetailedInfo name = "德国公寓">
			<Introduction>
外形简练、现代、充满活力，色彩大胆而时尚，属于现代简约派。
			</Introduction>
			<Style name = "德国建筑风格" Classification = "民族地域">德国建筑风格德国现代建筑简朴明快,色彩庄重,重视质量和功能,在现代世界建筑上占有重要地位。
			</Style>
		</DetailedInfo>
	</Image>
<!--71116214徐恩昊部分-->
	<Image ID = "11" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/11.jpg" Time = "2018-08-21">
			<Resolution>478*388</Resolution>
			<Format>jpg</Format>
			<Size>30.3KB</Size>
		</BasicInfo>
		<DetailedInfo name = "德国公寓">
			<Introduction>
功能讲求实用，任何被认为是多余的装饰都几乎被摒弃。
			</Introduction>
			<Style name = "德国建筑风格" Classification = "民族地域">德国建筑风格德国现代建筑简朴明快,色彩庄重,重视质量和功能,在现代世界建筑上占有重要地位。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "12" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/12.jpg" Time = "2018-08-21">
			<Resolution>319*478</Resolution>
			<Format>jpg</Format>
			<Size>26.5KB</Size>
		</BasicInfo>
		<DetailedInfo name = "北美别墅">
			<Introduction>
大窗、阁楼、坡屋顶、丰富的色彩和流畅的线条。
			</Introduction>
			<Style name = "北美建筑风格" Classification = "民族地域">北美建筑风格北美别墅发展成为既简约大气，又集各种建筑精华于一身的独特风格，充分体现了简洁大方、轻松的特点，居住常常具有人性化。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "13" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/13.jpg" Time = "2018-08-21">
			<Resolution>324*479</Resolution>
			<Format>jpg</Format>
			<Size>33.3KB</Size>
		</BasicInfo>
		<DetailedInfo name = "北美别墅楼梯">
			<Introduction>
街区氛围追求悠闲活力、自由开放。
			</Introduction>
			<Style name = "北美建筑风格" Classification = "民族地域">北美建筑风格北美别墅发展成为既简约大气，又集各种建筑精华于一身的独特风格，充分体现了简洁大方、轻松的特点，居住常常具有人性化。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "14" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/14.jpg" Time = "2018-08-21">
			<Resolution>479*327</Resolution>
			<Format>jpg</Format>
			<Size>32.8KB</Size>
		</BasicInfo>
		<DetailedInfo name = "北美别墅">
			<Introduction>
美式别墅多为木结构，体现了乡村感；运用侧山墙、双折线屋顶以及哥特式样的尖顶等比较典型的北美建筑的视觉符号；住宅类建筑个性化和多元化风格成分高。
			</Introduction>
			<Style name = "北美建筑风格" Classification = "民族地域">北美建筑风格北美别墅发展成为既简约大气，又集各种建筑精华于一身的独特风格，充分体现了简洁大方、轻松的特点，居住常常具有人性化。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "15" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/15.jpg" Time = "2018-08-21">
			<Resolution>474*479</Resolution>
			<Format>jpg</Format>
			<Size>50.5KB</Size>
		</BasicInfo>
		<DetailedInfo name = "合院建筑">
			<Introduction>
灰色坡屋顶、筒子瓦及一定高度的墙院围合方式。
			</Introduction>
			<Style name = "新中式建筑风格" Classification = "民族地域">新中式建筑风格中国传统的建筑主张“天人合一、浑然一体”，讲究“静”和“净”环境的平和和建筑的含蓄。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "16" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/16.jpg" Time = "2018-08-21">
			<Resolution>479*318</Resolution>
			<Format>jpg</Format>
			<Size>33.4KB</Size>
		</BasicInfo>
		<DetailedInfo name = "园林建筑">
			<Introduction>
“天人合一”的造园理念、精致的景观和空间处理手法独步天下。
			</Introduction>
			<Style name = "新中式建筑风格" Classification = "民族地域">新中式建筑风格中国传统的建筑主张“天人合一、浑然一体”，讲究“静”和“净”环境的平和和建筑的含蓄。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "17" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/17.jpg" Time = "2018-08-21">
			<Resolution>478*328</Resolution>
			<Format>jpg</Format>
			<Size>38.2KB</Size>
		</BasicInfo>
		<DetailedInfo name = "中式现代建筑">
			<Introduction>
新中式建筑通过现代材料和手法修改了传统建筑中的各个元素，并在此基础上进行必要的演化和抽象化，外貌上看不到传统建筑的原来模样，但在整体风格上，仍然保留着中式住宅的神韵和精髓。
			</Introduction>
			<Style name = "新中式建筑风格" Classification = "民族地域">新中式建筑风格中国传统的建筑主张“天人合一、浑然一体”，讲究“静”和“净”环境的平和和建筑的含蓄。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "18" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/18.jpg" Time = "2018-08-21">
			<Resolution>592*422</Resolution>
			<Format>jpg</Format>
			<Size>45.0KB</Size>
		</BasicInfo>
		<DetailedInfo name = "教堂">
			<Introduction>
采用古典柱式，主要是法国古典主义建筑，以及其他地区受它的影响的建筑。
			</Introduction>
			<Style name = "古典主义建筑风格" Classification = "历史发展潮流">古典主义建筑风格指在古希腊建筑和古罗马建筑的基础上发展起来的意大利文艺复兴建筑、巴洛克建筑和古典复兴建筑，其共同特点是采用古典柱式。
			</Style>
		</DetailedInfo>
	</Image>
	
	<Image ID = "19" Downloadable = "1">
		<BasicInfo Author = "wang1618" Source = "https://Shuo-Qi.github.io/Architecture/19.jpg" Time = "2018-08-21">
			<Resolution>720*514</Resolution>
			<Format>jpg</Format>
			<Size>62.6KB</Size>
		</BasicInfo>
		<DetailedInfo name = "图书馆">
			<Introduction>
新古典主义是从古典主义中提炼出的经典元素，包括线脚、檐口、栅花、圆柱等，淘汰了建筑史上所有怪诞的部分。
			</Introduction>
